name: Deploy Compute Application
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Deploy to Fastly
      uses: fastly/compute-actions@v2
      env:
        FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
